// This file automaticaly generated by MyEngine Shader Generator
// Date/time: 01/16/11 14:01:54
// DON'T EDIT this file or you may lost your changes!

#version 120

#define M_DIFFUSE(mat)  mat[0].rgba
#define M_AMBIENT(mat)  mat[1].rgba
#define M_SPECULAR(mat) mat[2].rgba
#define M_EMISSIVE(mat) mat[3].rgba

#define L_DIFFUSE(lig)  lig[0].rgba
#define L_AMBIENT(lig)  lig[1].rgba
#define L_SPECULAR(lig) lig[2].rgba
#define L_POSITION(lig) lig[3].xyz
#define L_RADIUS(lig)   lig[3].w

#define LERP(v1,v2,k) (v1+(v2-(v1))*(k))

attribute vec4 aPosition;
attribute vec2 aTCoord0;
attribute vec3 aNormal;

uniform mat4 uModelViewProjMatrix;
uniform mat4 uModelViewMatrix;
uniform mat3 uNormalMatrix;
uniform vec4 uGlobalAmbientColor;
uniform vec4 uMaterialColors[4];
uniform float uMaterialShininess;
uniform mat4 uLighting[4];

varying vec3 SeparateSpecular;

void main(void)
{
    vec3 position = vec3(uModelViewMatrix * aPosition);
    vec3 eyeVec = -normalize(position);
    vec3 normal = normalize(uNormalMatrix * aNormal);

    vec4 mDiffuse = M_DIFFUSE(uMaterialColors);
    vec4 mAmbient = M_AMBIENT(uMaterialColors);
    vec4 mSpecular = M_SPECULAR(uMaterialColors);
    vec4 mEmissive = M_EMISSIVE(uMaterialColors);

    vec3 specular = vec3(0.0,0.0,0.0);
    vec4 color = vec4(0.0, 0.0, 0.0, mDiffuse.a);
    color.rgb = uGlobalAmbientColor.rgb * mAmbient.rgb + mEmissive.rgb;
    
    // calculating lighting
    {
		int i = 0;
        vec4 lDiffuse  = L_DIFFUSE(uLighting[i]);
        vec4 lAmbient  = L_AMBIENT(uLighting[i]);
        vec4 lSpecular = L_SPECULAR(uLighting[i]);
        vec3 lPosition = L_POSITION(uLighting[i]);
        float lRadius  = L_RADIUS(uLighting[i]);
        vec3 lightVec = lPosition - position;
        float lDist = length(lightVec);
        lightVec = normalize(lightVec);
        float NdotL = max(dot(normal, lightVec), 0.0);
		float idx = min(lDist / lRadius, 1.0);
		float attenuation = -idx * idx + 1.0;
        color.rgb += attenuation * (
            NdotL * lDiffuse.rgb * mDiffuse.rgb + // diffuse component
            lAmbient.rgb * mAmbient.rgb // ambient component
            );
		vec3 reflVec = reflect(-lightVec, normal);
        float specPow = pow(max(dot(eyeVec, reflVec),0.0),  uMaterialShininess);
        // separate specular component
        specular +=
            attenuation * specPow * mSpecular.rgb * lSpecular.rgb;
    }
    {
		int i = 1;
        vec4 lDiffuse  = L_DIFFUSE(uLighting[i]);
        vec4 lAmbient  = L_AMBIENT(uLighting[i]);
        vec4 lSpecular = L_SPECULAR(uLighting[i]);
        vec3 lPosition = L_POSITION(uLighting[i]);
        float lRadius  = L_RADIUS(uLighting[i]);
        vec3 lightVec = lPosition - position;
        float lDist = length(lightVec);
        lightVec = normalize(lightVec);
        float NdotL = max(dot(normal, lightVec), 0.0);
		float idx = min(lDist / lRadius, 1.0);
		float attenuation = -idx * idx + 1.0;
        color.rgb += attenuation * (
            NdotL * lDiffuse.rgb * mDiffuse.rgb + // diffuse component
            lAmbient.rgb * mAmbient.rgb // ambient component
            );
		vec3 reflVec = reflect(-lightVec, normal);
        float specPow = pow(max(dot(eyeVec, reflVec),0.0),  uMaterialShininess);
        // separate specular component
        specular +=
            attenuation * specPow * mSpecular.rgb * lSpecular.rgb;
    }
    {
		int i = 2;
        vec4 lDiffuse  = L_DIFFUSE(uLighting[i]);
        vec4 lAmbient  = L_AMBIENT(uLighting[i]);
        vec4 lSpecular = L_SPECULAR(uLighting[i]);
        vec3 lPosition = L_POSITION(uLighting[i]);
        float lRadius  = L_RADIUS(uLighting[i]);
        vec3 lightVec = lPosition - position;
        float lDist = length(lightVec);
        lightVec = normalize(lightVec);
        float NdotL = max(dot(normal, lightVec), 0.0);
		float idx = min(lDist / lRadius, 1.0);
		float attenuation = -idx * idx + 1.0;
        color.rgb += attenuation * (
            NdotL * lDiffuse.rgb * mDiffuse.rgb + // diffuse component
            lAmbient.rgb * mAmbient.rgb // ambient component
            );
		vec3 reflVec = reflect(-lightVec, normal);
        float specPow = pow(max(dot(eyeVec, reflVec),0.0),  uMaterialShininess);
        // separate specular component
        specular +=
            attenuation * specPow * mSpecular.rgb * lSpecular.rgb;
    }
    {
		int i = 3;
        vec4 lDiffuse  = L_DIFFUSE(uLighting[i]);
        vec4 lAmbient  = L_AMBIENT(uLighting[i]);
        vec4 lSpecular = L_SPECULAR(uLighting[i]);
        vec3 lPosition = L_POSITION(uLighting[i]);
        float lRadius  = L_RADIUS(uLighting[i]);
        vec3 lightVec = lPosition - position;
        float lDist = length(lightVec);
        lightVec = normalize(lightVec);
        float NdotL = max(dot(normal, lightVec), 0.0);
		float idx = min(lDist / lRadius, 1.0);
		float attenuation = -idx * idx + 1.0;
        color.rgb += attenuation * (
            NdotL * lDiffuse.rgb * mDiffuse.rgb + // diffuse component
            lAmbient.rgb * mAmbient.rgb // ambient component
            );
		vec3 reflVec = reflect(-lightVec, normal);
        float specPow = pow(max(dot(eyeVec, reflVec),0.0),  uMaterialShininess);
        // separate specular component
        specular +=
            attenuation * specPow * mSpecular.rgb * lSpecular.rgb;
    }
	SeparateSpecular = specular;

    gl_FrontColor = color;
    gl_Position = uModelViewProjMatrix * aPosition;
    gl_TexCoord[0].xy = aTCoord0.xy;
}
